
name: Java CI with Maven
on:
  workflow_dispatch:
  # push:
  #   branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]
jobs:
  actions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
  setup-java:
    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '21'
  build-1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '21'
    - name: Build with Maven 1
      run: mvn -B package --file pom.xml
    - name: Archive JUnit Test Report
      uses: actions/upload-artifact@v2
      with:
        name: junit-test-report
        path: target/surefire-reports/*.xml
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Run JUnit Tests
      run: mvn test
  build-2:
    runs-on: ubuntu-latest
    steps:
    - name: Build with Maven 2
      run: mvn -B package --file pom.xml
  build-3:
    runs-on: ubuntu-latest
    steps:
    - name: Build with Maven 3
      run: mvn -B package --file pom.xml
  build-4:
    runs-on: ubuntu-latest
    steps:
    - name: Build with Maven 4
      run: mvn -B package --file pom.xml
  build-5:
    runs-on: ubuntu-latest
    steps:
    - name: Build with Maven 5
      run: mvn -B package --file pom.xml
  save-test-results:
    runs-on: ubuntu-latest
    steps:
    - name: Archive JUnit Test Report
      uses: actions/upload-artifact@v2
      with:
        name: junit-test-report
        path: target/surefire-reports/*.xml
  stage-1:
    runs-on: ubuntu-latest
    steps:
    - name: Stage
      run: mkdir staging && cp target/*.jar staging
  stage-2:
    runs-on: ubuntu-latest
    steps:
    - name: Stage
      run: mkdir staging && cp target/*.jar staging
  run-build:
    runs-on: ubuntu-latest
    steps:
    - name: Run JAR files
      run: |
        for jar_file in staging/*.jar; do
          mvn exec:java -Dexec.mainClass=me.opopescu.test_octane_github_actions.Main -Dexec.args=""
        done

